'use client';

// This file is generated by @atom8/image-to-react-component automatically
// DO NOT CHANGE IT MANUALLY!
import ComponentsCheckboxArrow from '../../assets/images/components/checkbox/arrow.svg';

type SvgProps = React.ComponentProps<'svg'> & { title?: string };

interface SvgIconCompProps extends SvgProps {}

export const ComponentsCheckboxArrowSvg = (props: SvgIconCompProps) => {
  return (
    <ComponentsCheckboxArrow
      {...props}
      fill={props.fill || 'currentColor'}
      viewBox={props.viewBox || '0 0 14 14'}
      width={props.width || '1em'}
      height={props.height || '1em'}
      style={{
        fontSize: props.fontSize || 'inherit',
        color: props.color || 'inherit',
        ...(props.style || {}),
      }}
    />
  );
};
