'use client';

// This file is generated by @atom8/image-to-react-component automatically
// DO NOT CHANGE IT MANUALLY!
import { CSSProperties, ReactNode } from 'react';
import omit from 'lodash/omit';
import Image from 'next/image';
import PagesForgotPasswordIcon from '../../assets/images/pages/forgot-password/icon.png';

type ExtractProps<T> = T extends React.ForwardRefExoticComponent<infer P> ? P : never;
type ImageProps = ExtractProps<typeof Image>;

interface ImageCompProps extends Omit<ImageProps, 'src'> {
  className?: string;
  style?: CSSProperties;
  /** 是否自动设置大小 */
  noSize?: boolean;
  src?: string;
  children?: ReactNode;
}
export const PagesForgotPasswordIconImage = (props: ImageCompProps) => {
  const { src, noSize } = props;
  const renderProps = () => {
    return {
      src: src || PagesForgotPasswordIcon.src,
      ...(!noSize
        ? {
            width: 344,
            height: 394,
          }
        : {}),
    };
  };

  return <Image {...omit(props, 'noSize')} {...renderProps()} alt={props.alt} />;
};

export const PagesForgotPasswordIconBackground = (props: ImageCompProps) => {
  const { className, noSize, style, children } = props;
  return (
    <div
      className={className}
      style={{
        ...(!noSize
          ? {
              width: 344,
              height: 394,
            }
          : {}),
        backgroundImage: `url(${PagesForgotPasswordIcon.src})`,
        backgroundSize: '100% 100%',
        backgroundRepeat: 'no-repeat',
        ...style,
      }}
    >
      {children}
    </div>
  );
};
